import 'package:ugd_4_hospital/component/dataKelompok.dart';

const isi = [
  Kelompok(
    id: '1',
    profile: 'images/f8744aa8-12e1-4368-ab3f-5b53627bb217.jpeg',
    nama: 'Vigo',
    gender: 'M',
    email: 'Vigo@gmail.com',
    umur: 20,
    universitas: 'Atma Jaya Yogyakarta',
    programStudi: 'Informatika',
    npm: 210711303,
  ),
  Kelompok(
    id: '2',
    profile: 'images/arren.jpeg',
    nama: 'Alex',
    gender: 'M',
    email: 'Alex@gmail.com',
    umur: 20,
    universitas: 'Atma Jaya Yogyakarta',
    programStudi: 'Informatika',
    npm: 210711407,
  ),
  Kelompok(
    id: '3',
    profile: 'images/AAA.jpeg',
    nama: 'Axel',
    gender: 'M',
    email: 'Axel@gmail.com',
    umur: 20,
    universitas: 'Atma Jaya Yogyakarta',
    programStudi: 'Informatika',
    npm: 210711114,
  ),
  Kelompok(
    id: '4',
    profile: 'images/josh.jpg',
    nama: 'Amanda',
    gender: 'F',
    email: 'amanda@gmail.com',
    umur: 20,
    universitas: 'Atma Jaya Yogyakarta',
    programStudi: 'Informatika',
    npm: 210711486,
  ),
  Kelompok(
    id: '5',
    profile: 'images/gus.jpg',
    nama: 'Zidane',
    gender: 'M',
    email: 'zidezidane@gmail.com',
    umur: 20,
    universitas: 'Atma Jaya Yogyakarta',
    programStudi: 'Informatika',
    npm: 200710902,
  ),
];
